// dashboard/src/app/(dashboard)/profiles/page.tsx
'use client';

import DashboardInset from '@/components/dashboard/inset';
import { useAuth } from '@clerk/nextjs';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { deleteProfile, getProfiles } from './actions';
import { usePage } from '@/hooks/use-page';
import { toast } from 'sonner';
import type { ColumnDef, Row } from '@tanstack/react-table';
import { Eye, MoreVertical, RefreshCw, Trash } from 'lucide-react';
import { formatDate } from '@/utils/date';
import { mapToDropdownMenuItems, type DropdownItem } from '@/utils/dropdown';
import { copyToClipboard } from '@/utils/clipboard';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Button } from '@/components/ui/button';
import { redirect } from 'next/navigation';
import Link from 'next/link';
import { Loading } from '@/components/loading';
import { SearchField } from '@/components/search-field';
import Alert from '@/components/alert';
import { DataTable } from '@/components/dashboard/data-table';
import { Nothing } from '@/components/nothing';
import { useSearch } from '@/hooks/use-search';
import type { Profile } from 'database/generated/prisma/client';
import { toUnixTimestamps } from '@root/utils/date';

export default function ProfilesPage() {
  const { isSignedIn, isLoaded } = useAuth();

  const [search] = useSearch();
  const [page] = usePage();

  const queryClient = useQueryClient();
  const {
    data: profiles,
    isLoading,
    isRefetching,
    isSuccess,
    isError,
    error,
    refetch,
  } = useQuery({
    enabled: !!isSignedIn,
    queryKey: ['profiles', search, page],
    queryFn: () => getProfiles(search, page),
  });

  const deleteMutation = useMutation({
    mutationFn: (id: string) => deleteProfile(id),
    onMutate: () => {
      const toastId = toast.loading('Deleting profile...');
      return { toastId };
    },
    onSuccess: (_, __, context) => {
      queryClient.invalidateQueries({ queryKey: ['profiles'] });
      toast.success('Profile deleted', {
        id: context.toastId,
      });
    },
    onError: (err, _, context) => {
      toast.error('Failed to delete phrase', {
        id: context?.toastId,
        description: err.message,
      });
    },
  });

  type Response = Omit<Profile, 'bio'>;

  const columns: Array<ColumnDef<Response>> = [
    {
      accessorKey: 'id',
      header: '#',
    },
    {
      accessorKey: 'discordId',
      header: 'Discord ID',
    },
    {
      accessorKey: 'nickname',
      header: 'Nickname',
      cell: ({ row }) => row.original.nickname || <Nothing />,
    },
    {
      accessorKey: 'createdAt',
      header: 'Created At',
      cell: ({ row }) => formatDate(row.original.createdAt),
    },
    {
      accessorKey: 'updatedAt',
      header: 'Updated At',
      cell: ({ row }) => formatDate(row.original.updatedAt),
    },
    {
      id: 'actions',
      cell: ({ row }) => (
        <div className="ml-2 space-x-2 text-right">
          <Button variant="secondary" size="icon-sm" asChild>
            <Link href={`/profiles/${row.original.id}`}>
              <Eye />
            </Link>
          </Button>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" size="icon-sm">
                <span className="sr-only">Open Menu</span>
                <MoreVertical />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              {mapToDropdownMenuItems(getRowActions(row))}
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      ),
    },
  ];

  const getRowActions = (row: Row<Response>): Array<DropdownItem> => [
    {
      label: 'Copy ID',
      onClick: () => copyToClipboard(row.original.id, 'ID'),
    },
    {
      label: 'Copy Discord ID',
      onClick: () => copyToClipboard(row.original.discordId, 'Discord ID'),
    },
    {
      label: 'Copy Nickname',
      onClick: () => copyToClipboard(row.original.nickname || '', 'Nickname'),
    },
    {
      label: 'Copy Created Timestamp',
      onClick: () =>
        copyToClipboard(
          toUnixTimestamps(row.original.createdAt.getTime()).toString(),
          'Created Timestamp',
        ),
    },
    {
      label: 'Copy Updated Timestamp',
      onClick: () =>
        copyToClipboard(
          toUnixTimestamps(row.original.updatedAt.getTime()).toString(),
          'Updated Timestamp',
        ),
    },
    { type: 'separator' },
    {
      label: 'Delete',
      variant: 'destructive',
      icon: <Trash />,
      onClick: () => deleteMutation.mutate(row.original.id),
    },
  ];

  if (!isLoaded) return <Loading description="Checking authentication..." />;
  if (!isSignedIn) redirect('/sign-in');

  return (
    <DashboardInset
      breadcrumbs={[
        {
          title: 'Profiles',
          href: '/profiles',
        },
      ]}
    >
      <div className="space-y-4">
        <div className="flex flex-row items-center justify-between gap-x-2">
          <SearchField name="profiles" />
          <Button
            variant="outline"
            size="icon"
            onClick={() => refetch()}
            disabled={isLoading || isRefetching}
          >
            <RefreshCw />
          </Button>
        </div>
        {isLoading && <Loading description="Loading profiles..." />}
        {isError && (
          <Alert
            title="Failed to load profiles"
            description={error.message}
            variant="destructive"
          />
        )}
        {isSuccess && (
          <DataTable
            data={profiles.data || []}
            columns={columns}
            onRefresh={refetch}
            enablePagination={true}
            pageCount={profiles.pageCount}
          />
        )}
      </div>
    </DashboardInset>
  );
}

// dashboard/app/pages/(manage)/profiles/index.vue
<script setup lang="ts">
import type { DropdownMenuItem, TableColumn } from '@nuxt/ui';
import { useMutation, useQuery, useQueryClient } from '@tanstack/vue-query';
import type { Row } from '@tanstack/vue-table';
import type { Profile } from 'database/schemas/schema';

const appConfig = useAppConfig();

const toast = useToast();
const { copy } = useClipboard();

const UuuidRender = resolveComponent('UuidRender');
const UIcon = resolveComponent('UIcon');
const UButton = resolveComponent('UButton');
const UDropdownMenu = resolveComponent('UDropdownMenu');

const searchTerm = ref('');

const queryClient = useQueryClient();
const {
  data: profiles,
  isLoading,
  isRefetching,
  isError,
  error,
  refetch,
} = useQuery({
  queryKey: ['profiles', searchTerm],
  queryFn: () =>
    $fetch<Profile[]>('/api/profiles', {
      query: {
        searchTerm: searchTerm.value,
      },
    }),
});

const deleteMutation = useMutation({
  mutationFn: (id: string) =>
    $fetch(`/api/profiles/${id}`, {
      method: 'DELETE',
    }),
  onMutate: (id) => {
    loadingToast.create(toast, `delete-profile-${id}`, {
      title: 'Deleting profile...',
    });
  },
  onSuccess: (_, id) => {
    queryClient.invalidateQueries({ queryKey: ['profiles'] });
    loadingToast.update(toast, `delete-profile-${id}`, {
      title: 'Profile deleted',
      color: 'success',
      icon: appConfig.ui.icons.success,
    });
  },
  onError: (error, id) => {
    loadingToast.update(toast, `delete-profile-${id}`, {
      title: 'Failed to delete profile',
      description: error?.message,
      color: 'error',
      icon: appConfig.ui.icons.error,
    });
  },
});

const columns: TableColumn<Profile>[] = [
  {
    accessorKey: 'id',
    header: '#',
    cell: ({ row }) => h(UuuidRender, { uuid: row.original.id }),
  },
  {
    accessorKey: 'discordId',
    header: 'Discord ID',
  },
  {
    accessorKey: 'nickname',
    header: 'Nickname',
    cell: ({ row }) =>
      row.original.nickname || h(UIcon, { name: appConfig.ui.icons.nothing }),
  },
  {
    accessorKey: 'bio',
    header: 'Bio',
    cell: ({ row }) =>
      row.original.bio
        ? h(
            'span',
            { class: 'whitespace-pre truncate max-w-xs block' },
            row.original.bio,
          )
        : h(UIcon, { name: appConfig.ui.icons.nothing }),
  },
  {
    accessorKey: 'createdAt',
    header: 'Created At',
    cell: ({ row }) => formatDate(new Date(row.original.createdAt)),
  },
  {
    id: 'actions',
    cell: ({ row }) =>
      h(
        'div',
        { class: 'text-right' },
        h(
          UDropdownMenu,
          {
            content: {
              align: 'end',
            },
            items: getRowActions(row),
            'aria-label': 'Profile actions',
          },
          () =>
            h(UButton, {
              icon: appConfig.ui.icons.menuVertical,
              color: 'neutral',
              variant: 'ghost',
              class: 'ml-auto',
              'aria-label': 'Open actions menu',
            }),
        ),
      ),
  },
];

const getRowActions = (row: Row<Profile>) => {
  const actions: DropdownMenuItem[] = [
    {
      label: 'View details',
      icon: appConfig.ui.icons.eye,
      to: `/profiles/${row.original.id}`,
    },
    { type: 'separator' },
    {
      label: 'Copy ID',
      onSelect: () => copyToClipboard(copy, toast.add, row.original.id, 'ID'),
    },
    {
      label: 'Copy Discord ID',
      onSelect: () =>
        copyToClipboard(copy, toast.add, row.original.discordId, 'Discord ID'),
    },
  ];

  if (row.original.nickname)
    actions.push({
      label: 'Copy Nickname',
      onSelect: () =>
        copyToClipboard(copy, toast.add, row.original.nickname!, 'Nickname'),
    });
  if (row.original.bio)
    actions.push({
      label: 'Copy Bio',
      onSelect: () =>
        copyToClipboard(copy, toast.add, row.original.bio!, 'Bio'),
    });

  actions.push(
    {
      label: 'Copy Unix Timestamp',
      onSelect: () =>
        copyToClipboard(
          copy,
          toast.add,
          new Date(row.original.createdAt).getTime().toString(),
          'Unix Timestamp',
        ),
    },
    { type: 'separator' },
    {
      label: 'Delete',
      color: 'error',
      icon: appConfig.ui.icons.trash,
      onSelect: () => deleteMutation.mutate(row.original.id),
    },
  );

  return actions;
};
</script>

<template>
  <UDashboardPanel id="profiles">
    <template #header>
      <UDashboardNavbar title="Profiles">
        <template #leading>
          <UDashboardSidebarCollapse />
        </template>

        <template #right>
          <UButton
            :icon="appConfig.ui.icons.reload"
            color="neutral"
            variant="subtle"
            :disabled="isLoading"
            :loading="isRefetching"
            @click="() => void refetch()"
          />
        </template>
      </UDashboardNavbar>
    </template>

    <template #body>
      <div class="space-y-6">
        <SearchField
          name="profiles"
          class="w-full max-w-md"
          @update:value="(value) => (searchTerm = value)"
        />
        <UAlert
          v-if="isError"
          color="error"
          variant="subtle"
          title="Failed to load profiles"
          :description="error?.message"
          :icon="appConfig.ui.icons.error"
          :actions="[
            {
              label: 'Retry',
              color: 'error',
              size: 'md',
              onClick: () => void refetch(),
            },
          ]"
        />
        <UTable
          v-else
          :data="profiles"
          :columns="columns"
          :loading="isLoading || isRefetching"
          class="shrink-0"
        />
      </div>
    </template>
  </UDashboardPanel>
</template>
