// dashboard-next/src/app/(dashboard)/phrases/page.tsx
'use client';
import DashboardInset from '@/components/dashboard/inset';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { deletePhrase, getPhrases } from './actions';
import { SearchField } from '@/components/search-field';
import { Button } from '@/components/ui/button';
import { MoreVertical, RefreshCw, Trash } from 'lucide-react';
import { useAuth } from '@clerk/nextjs';
import { redirect } from 'next/navigation';
import { DataTable } from '@/components/dashboard/data-table';
import type { ColumnDef, Row } from '@tanstack/react-table';
import type { Phrase } from 'database/schemas/schema';
import { UUIDRender } from '@/components/uuid-render';
import { formatDate } from '@/utils/date';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { mapToDropdownMenuItems, type DropdownItem } from '@/utils/dropdown';
import { copyToClipboard } from '@/utils/clipboard';
import { toast } from 'sonner';
import { Loading } from '@/components/loading';
import Alert from '@/components/alert';
import { NewPhraseDialog } from './dialog';
import { usePage } from '@/hooks/use-page';

export default function PhrasesPage() {
  const [searchTerm, setSearchTerm] = useState('');
  const { isSignedIn, isLoaded } = useAuth();

  const page = usePage();

  const queryClient = useQueryClient();
  const {
    data: phrases,
    isLoading,
    isRefetching,
    isSuccess,
    isError,
    error,
    refetch,
  } = useQuery({
    enabled: !!isSignedIn,
    queryKey: ['phrases', searchTerm, page],
    queryFn: () => getPhrases(searchTerm, page),
  });

  const deleteMutation = useMutation({
    mutationFn: (id: string) => deletePhrase(id),
    onMutate: () => {
      const toastId = toast.loading('Deleting phrase...');
      return { toastId };
    },
    onSuccess: (_, __, context) => {
      queryClient.invalidateQueries({ queryKey: ['phrases'] });
      toast.success('Phrase deleted', {
        id: context.toastId,
      });
    },
    onError: (error, _, context) => {
      toast.error(`Failed to delete phrase`, {
        id: context?.toastId,
        description: error.message,
      });
    },
  });

  const columns: Array<ColumnDef<Phrase>> = [
    {
      accessorKey: 'id',
      header: '#',
      cell: ({ row }) => <UUIDRender value={row.original.id} />,
    },
    {
      accessorKey: 'content',
      header: 'Content',
      cell: ({ row }) => (
        <span className="whitespace-pre">{row.original.content}</span>
      ),
    },
    {
      accessorKey: 'source',
      header: 'Source',
      cell: ({ row }) => (
        <span className="whitespace-pre">
          {row.original.source.replace(/;\s/g, '\n')}
        </span>
      ),
    },
    {
      accessorKey: 'createdAt',
      header: 'Created At',
      cell: ({ row }) => formatDate(row.original.createdAt),
    },
    {
      id: 'actions',
      cell: ({ row }) => (
        <div className="ml-2 text-right">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" size="icon-sm">
                <span className="sr-only">Open Menu</span>
                <MoreVertical />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              {mapToDropdownMenuItems(getRowActions(row))}
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      ),
    },
  ];

  const getRowActions = (row: Row<Phrase>): Array<DropdownItem> => [
    {
      label: 'Copy ID',
      onClick: () => copyToClipboard(row.original.id, 'ID'),
    },
    {
      label: 'Copy Content',
      onClick: () => copyToClipboard(row.original.content, 'Content'),
    },
    {
      label: 'Copy Source',
      onClick: () => copyToClipboard(row.original.source, 'Source'),
    },
    {
      label: 'Copy Unix Timestamp',
      onClick: () =>
        copyToClipboard(
          row.original.createdAt.getTime().toString(),
          'Unix Timestamp',
        ),
    },
    { type: 'separator' },
    {
      label: 'Delete',
      variant: 'destructive',
      icon: <Trash />,
      onClick: () => deleteMutation.mutate(row.original.id),
    },
  ];

  if (!isLoaded) return <Loading description="Checking authentication..." />;
  if (!isSignedIn) redirect('/sign-in');

  return (
    <DashboardInset
      breadcrumbs={[
        {
          title: 'Phrases',
          href: '/phrases',
        },
      ]}
    >
      <div className="space-y-4">
        <div className="flex flex-row items-center justify-between gap-x-2">
          <SearchField name="phrases" onSearch={setSearchTerm} />
          <div className="flex flex-row gap-x-2">
            <NewPhraseDialog queryClient={queryClient} />
            <Button
              variant="outline"
              size="icon"
              onClick={() => refetch()}
              disabled={isLoading || isRefetching}
            >
              <RefreshCw />
            </Button>
          </div>
        </div>
        {isLoading && <Loading description="Fetching phrases..." />}
        {isSuccess && (
          <DataTable
            data={phrases.data || []}
            columns={columns}
            onRefresh={refetch}
            enablePagination={true}
            pageCount={phrases.pageCount}
            pageIndex={phrases.pageIndex}
            createComponent={
              <NewPhraseDialog queryClient={queryClient} slick={true} />
            }
          />
        )}
        {isError && (
          <Alert
            title="Failed to load phrases"
            description={error.message}
            variant="destructive"
          />
        )}
      </div>
    </DashboardInset>
  );
}

// dashboard/app/pages/(manage)/phrases/index.vue
<script setup lang="ts">
import type { TableColumn } from '@nuxt/ui';
import { useMutation, useQuery, useQueryClient } from '@tanstack/vue-query';
import type { Phrase } from 'database/schemas/schema';
import type { Row } from '@tanstack/vue-table';
import copyToClipboard from '~/utils/copyToClipboard';

const toast = useToast();
const { copy } = useClipboard();

const UuidRender = resolveComponent('UuidRender');
const UButton = resolveComponent('UButton');
const UDropdownMenu = resolveComponent('UDropdownMenu');

const searchTerm = ref('');

const queryClient = useQueryClient();
const {
  data: phrases,
  isLoading,
  isRefetching,
  isError,
  error,
  refetch,
} = useQuery({
  queryKey: ['phrases', searchTerm],
  queryFn: () =>
    $fetch<Phrase[]>('/api/phrases', {
      query: {
        searchTerm: searchTerm.value,
      },
    }),
});

const deleteMutation = useMutation({
  mutationFn: (id: string) =>
    $fetch(`/api/phrases/${id}`, {
      method: 'DELETE',
    }),
  onSuccess: () => {
    queryClient.invalidateQueries({ queryKey: ['phrases'] });
    toast.add({
      title: 'Phrase deleted',
      color: 'success',
      icon: 'lucide:circle-check',
    });
  },
  onError: (error) => {
    toast.add({
      title: 'Failed to delete phrase',
      description: error?.message,
      color: 'error',
      icon: 'lucide:circle-alert',
    });
  },
});

const columns: TableColumn<Phrase>[] = [
  {
    accessorKey: 'id',
    header: '#',
    cell: ({ row }) => h(UuidRender, { uuid: row.original.id }),
  },
  {
    accessorKey: 'content',
    header: 'Content',
    cell: ({ row }) =>
      h('span', { class: 'whitespace-pre' }, row.original.content),
  },
  {
    accessorKey: 'source',
    header: 'Source',
    cell: ({ row }) =>
      h(
        'span',
        { class: 'whitespace-pre' },
        row.original.source.replace(/;\s/g, '\n'),
      ),
  },
  {
    accessorKey: 'createdAt',
    header: 'Created At',
    cell: ({ row }) => formatDate(new Date(row.original.createdAt)),
  },
  {
    id: 'actions',
    cell: ({ row }) =>
      h(
        'div',
        { class: 'text-right' },
        h(
          UDropdownMenu,
          {
            content: {
              align: 'end',
            },
            items: getRowActions(row),
            'aria-label': 'Actions dropdown',
          },
          () =>
            h(UButton, {
              icon: 'lucide:ellipsis-vertical',
              color: 'neutral',
              variant: 'ghost',
              class: 'ml-auto',
              'aria-label': 'Actions dropdown',
            }),
        ),
      ),
  },
];

const getRowActions = (row: Row<Phrase>) => [
  {
    type: 'label',
    label: 'Actions',
  },
  {
    label: 'Copy ID',
    onSelect: () => copyToClipboard(copy, toast.add, row.original.id, 'ID'),
  },
  {
    label: 'Copy Content',
    onSelect: () =>
      copyToClipboard(copy, toast.add, row.original.content, 'Content'),
  },
  {
    label: 'Copy Source',
    onSelect: () =>
      copyToClipboard(copy, toast.add, row.original.source, 'Source'),
  },
  {
    label: 'Copy Unix Timestamp',
    onSelect: () =>
      copyToClipboard(
        copy,
        toast.add,
        new Date(row.original.createdAt).getTime().toString(),
        'Unix Timestamp',
      ),
  },
  { type: 'separator' },
  {
    label: 'Delete',
    color: 'error',
    icon: 'lucide:trash',
    onSelect: () => deleteMutation.mutate(row.original.id),
  },
];
</script>

<template>
  <UDashboardPanel id="phrases">
    <template #header>
      <UDashboardNavbar title="Phrases">
        <template #leading>
          <UDashboardSidebarCollapse />
        </template>
      </UDashboardNavbar>
    </template>

    <template #body>
      <div class="space-y-4">
        <div class="flex items-center justify-between gap-x-2">
          <SearchField
            name="phrases"
            class="w-full max-w-md"
            @update:value="(value) => (searchTerm = value)"
          />
          <div class="flex items-center gap-x-2">
            <PhrasesAddModal :query-client="queryClient" />
            <UButton
              icon="lucide:refresh-cw"
              color="neutral"
              variant="subtle"
              :disabled="isLoading || isRefetching"
              @click="() => void refetch()"
            />
          </div>
        </div>
        <UAlert
          v-if="isError"
          color="error"
          variant="subtle"
          title="Failed to load phrases"
          :description="error?.message"
          icon="lucide:circle-alert"
          :actions="[
            {
              label: 'Retry',
              color: 'error',
              size: 'md',
              onClick: () => void refetch(),
            },
          ]"
        />
        <UTable
          v-else
          :data="phrases"
          :columns="columns"
          :loading="isLoading"
          class="flex-1"
        />
      </div>
    </template>
  </UDashboardPanel>
</template>
